# Generated by Django 4.2.11 on 2026-01-05 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('corporate_tax', '법인세'), ('income_tax', '소득세'), ('vat', '부가가치세'), ('comprehensive_income', '종합소득세'), ('other', '기타')], max_length=50, verbose_name='상담 유형')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(max_length=128, verbose_name='전화번호')),
                ('password_hash', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('message', models.TextField(blank=True, verbose_name='상담 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '상담 신청',
                'verbose_name_plural': '상담 신청 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consultation/%Y/%m/%d/', verbose_name='첨부파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='consultations.consultation', verbose_name='상담 신청')),
            ],
            options={
                'verbose_name': '상담 첨부파일',
                'verbose_name_plural': '상담 첨부파일 목록',
            },
        ),
    ]
