# Generated by Django 4.2.11 on 2026-01-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', '접수대기'), ('in_progress', '진행중'), ('completed', '완료')], default='pending', max_length=20, verbose_name='상담 상태'),
        ),
    ]
