# Generated by Django 4.2.11 on 2026-01-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='admin_response',
            field=models.TextField(blank=True, verbose_name='관리자 답변'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='respoonsed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='답변일시'),
        ),
    ]
