# Generated by Django 4.2.11 on 2026-01-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_admin_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='respoonsed_at',
            new_name='responded_at',
        ),
    ]
